import {
  boolean,
  doublePrecision,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uuid,
} from 'drizzle-orm/pg-core';

export const gyms = pgTable('gyms', {
  id: uuid('id').primaryKey(),
  name: text('name').notNull(),
  website: text('website'),
  email: text('email'),
  phone: text('phone'),
  instagram: text('instagram'),
  address: text('address'),
  postcode: text('postcode'),
  city: text('city'),
  borough: text('borough'),
  region: text('region'),
  country: text('country'),
  nearestTransport: text('nearest_transport'),
  headCoach: text('head_coach'),
  coaches: jsonb('coaches').$type<string[]>(),
  lineage: text('lineage'),
  styleFocus: text('style_focus'),
  affiliation: text('affiliation'),
  gi: boolean('gi'),
  nogi: boolean('nogi'),
  openMat: boolean('open_mat'),
  dropIn: boolean('drop_in'),
  verified: boolean('verified'),
  source: text('source'),
  extraWebsites: text('extra_websites').array(),
  osmUrl: text('osm_url'),
  tags: jsonb('tags').$type<Record<string, unknown>>(),
  lat: doublePrecision('lat'),
  lon: doublePrecision('lon'),
  communityScore: numeric('community_score'),
  foundedYear: integer('founded_year'),
  updatedAt: timestamp('updated_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }),
});

export type GymRow = typeof gyms.$inferSelect;
